# Generated by Django 5.1.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverdueSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("threshold_days", models.IntegerField(default=30, verbose_name="逾期天数门槛")),
            ],
        ),
        migrations.CreateModel(
            name="OverdueEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("aid_code", models.CharField(max_length=40, verbose_name="航标编号")),
                ("threshold_days", models.IntegerField(verbose_name="当时天数门槛")),
                ("entered_at", models.DateTimeField(auto_now_add=True, verbose_name="进入时刻")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="解除时刻")),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overdue_events",
                        to="inspection.inspection",
                        verbose_name="所依不合格实测",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
